language: node_js

sudo: required
addons:
 chrome: stable

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - "8"

notifications:
  email:
    on_success: never
    on_failure: never

script:
  - npm test

after_script:
  - npm install -g codecov
  - cat ./coverage/lcov.info | codecov
